In [ ]:
# read it in to inspect it
with open('/content/drive/MyDrive/Colab Notebooks/tutunamayanlar.txt', 'r', encoding='utf-8') as f:
    text = f.read()

In [ ]:
print("length of dataset in characters: ", len(text))

length of dataset in characters:  1266381


In [ ]:
print(text[:1000])

Birinci Bölüm 


23 



1 

Olay, XX. yüzyılın ikinci yarısında, bir gece, Turgut’un evin¬ 
de başlamıştı. O zamanlar daha Olric yoktu, daha o zaman¬ 
lar Turgut’un kafası bu kadar karışık değildi. Bir gece yarısı 
evinde oturmuş düşünüyordu. Selim, arkasından bir de 
herkesin bu durumlarda yaptığı gibi, mektuba benzer bir 
şey bırakarak, bu dünyadan birkaç gün önce kendi isteğiyle 
ayrılıp gitmişti. Turgut, bu mektubu çalışma masasının üs¬ 
tüne koymuş, karşısında oturup duruyordu. Selim’in titrek 
bir yazıyla karaladığı satırlar gözlerinin önünde uçuşuyor¬ 
du. Harflerin arasında arkadaşının uzun parmaklarını seçer 
gibi oluyor, okuduğu kelimelerle birlikte onun kaim ve bo¬ 
ğuk sesini duyduğunu sanıyordu. 

O zamanlar, henüz, Olric yoktu; hava raporları da günlük 
bültenlerden sonra okunmuyordu. Henüz durum, bugünkü 
gibi açık ve seçik, bir bakıma da belirsiz değildi. 

“Bu mektup, neden geldi beni buldu?” diye söyleniyordu 
hafifçe. Demek, hafifçe söylenme alışkanlığı, o zamana ka¬

In [ ]:
# here are all the unique characters that occur in this text
chars = sorted(list(set(text)))
vocab_size = len(chars)
print(''.join(chars))
print(vocab_size)


 !'(),-./0123456789:;?ABCDEFGHIJKLMNOPRSTUVWXYZabcdefghijklmnopqrstuvwxyz¬ÂÇÖÛÜâçîöûüĞğİıŞş‘’“”
96


In [ ]:
# create a mapping from characters to integers
stoi = { ch:i for i,ch in enumerate(chars) }
itos = { i:ch for i,ch in enumerate(chars) }
encode = lambda s: [stoi[c] for c in s] # encoder: take a string, output a list of integers
decode = lambda l: ''.join([itos[i] for i in l]) # decoder: take a list of integers, output a string

print(encode("hii there"))
print(decode(encode("hii there")))
#very basic char based tokenizer

[55, 56, 56, 1, 67, 55, 52, 65, 52]
hii there


In [ ]:
# let's now encode the entire text dataset and store it into a torch.Tensor
import torch
data = torch.tensor(encode(text), dtype=torch.long)
print(data.shape, data.dtype)
print(data[:1000]) # the 1000 characters we looked at earier will to the GPT look like this
#in order to use in torch lib we need to store it in a torch tensor format

torch.Size([1266381]) torch.int64
tensor([24, 56, 65, 56, 61, 50, 56,  1, 24, 83, 59, 85, 60,  1,  0,  0,  0, 12,
        13,  1,  0,  0,  0,  0, 11,  1,  0,  0, 37, 59, 48, 72,  6,  1, 45, 45,
         8,  1, 72, 85, 73, 72, 89, 59, 89, 61,  1, 56, 58, 56, 61, 50, 56,  1,
        72, 48, 65, 89, 66, 89, 61, 51, 48,  6,  1, 49, 56, 65,  1, 54, 52, 50,
        52,  6,  1, 41, 68, 65, 54, 68, 67, 93, 68, 61,  1, 52, 69, 56, 61, 74,
         1,  0, 51, 52,  1, 49, 48, 91, 59, 48, 60, 89, 91, 67, 89,  8,  1, 37,
         1, 73, 48, 60, 48, 61, 59, 48, 65,  1, 51, 48, 55, 48,  1, 37, 59, 65,
        56, 50,  1, 72, 62, 58, 67, 68,  6,  1, 51, 48, 55, 48,  1, 62,  1, 73,
        48, 60, 48, 61, 74,  1,  0, 59, 48, 65,  1, 41, 68, 65, 54, 68, 67, 93,
        68, 61,  1, 58, 48, 53, 48, 66, 89,  1, 49, 68,  1, 58, 48, 51, 48, 65,
         1, 58, 48, 65, 89, 91, 89, 58,  1, 51, 52, 87, 56, 59, 51, 56,  8,  1,
        24, 56, 65,  1, 54, 52, 50, 52,  1, 72, 48, 65, 89, 66, 89,  1,  0, 52,
      

In [ ]:
# Let's now split up the data into train and validation sets
n = int(0.9*len(data)) # first 90% will be train, rest val
train_data = data[:n]
val_data = data[n:]

In [ ]:
block_size = 8
train_data[:block_size+1]

tensor([24, 56, 65, 56, 61, 50, 56,  1, 24])

In [ ]:
x = train_data[:block_size]
y = train_data[1:block_size+1]
for t in range(block_size):
    context = x[:t+1]
    target = y[t]
    print(f"when input is {context} the target: {target}")

when input is tensor([24]) the target: 56
when input is tensor([24, 56]) the target: 65
when input is tensor([24, 56, 65]) the target: 56
when input is tensor([24, 56, 65, 56]) the target: 61
when input is tensor([24, 56, 65, 56, 61]) the target: 50
when input is tensor([24, 56, 65, 56, 61, 50]) the target: 56
when input is tensor([24, 56, 65, 56, 61, 50, 56]) the target: 1
when input is tensor([24, 56, 65, 56, 61, 50, 56,  1]) the target: 24


In [ ]:
torch.manual_seed(1337)
batch_size = 4 # how many independent sequences will we process in parallel?
block_size = 8 # what is the maximum context length for predictions?

def get_batch(split):
    # generate a small batch of data of inputs x and targets y
    data = train_data if split == 'train' else val_data
    ix = torch.randint(len(data) - block_size, (batch_size,))
    x = torch.stack([data[i:i+block_size] for i in ix])
    y = torch.stack([data[i+1:i+block_size+1] for i in ix])
    return x, y
#data loader

xb, yb = get_batch('train')
print('inputs:')
print(xb.shape)
print(xb)
print('targets:')
print(yb.shape)
print(yb)

print('----')

for b in range(batch_size): # batch dimension
    for t in range(block_size): # time dimension
        context = xb[b, :t+1]
        target = yb[b,t]
        print(f"when input is {context.tolist()} the target: {target}")

inputs:
torch.Size([4, 8])
tensor([[68,  1, 51, 56, 74,  1,  0, 72],
        [69, 52,  1, 51, 62, 66, 67, 59],
        [51, 52,  1,  0,  0,  0, 16, 14],
        [ 1, 81, 48, 59, 89, 91, 60, 48]])
targets:
torch.Size([4, 8])
tensor([[ 1, 51, 56, 74,  1,  0, 72, 52],
        [52,  1, 51, 62, 66, 67, 59, 48],
        [52,  1,  0,  0,  0, 16, 14, 13],
        [81, 48, 59, 89, 91, 60, 48, 61]])
----
when input is [68] the target: 1
when input is [68, 1] the target: 51
when input is [68, 1, 51] the target: 56
when input is [68, 1, 51, 56] the target: 74
when input is [68, 1, 51, 56, 74] the target: 1
when input is [68, 1, 51, 56, 74, 1] the target: 0
when input is [68, 1, 51, 56, 74, 1, 0] the target: 72
when input is [68, 1, 51, 56, 74, 1, 0, 72] the target: 52
when input is [69] the target: 52
when input is [69, 52] the target: 1
when input is [69, 52, 1] the target: 51
when input is [69, 52, 1, 51] the target: 62
when input is [69, 52, 1, 51, 62] the target: 66
when input is [69, 52, 1, 5

In [ ]:
print(xb) # our input to the transformer

tensor([[68,  1, 51, 56, 74,  1,  0, 72],
        [69, 52,  1, 51, 62, 66, 67, 59],
        [51, 52,  1,  0,  0,  0, 16, 14],
        [ 1, 81, 48, 59, 89, 91, 60, 48]])


In [ ]:
import torch
import torch.nn as nn
from torch.nn import functional as F
torch.manual_seed(1337)

class BigramLanguageModel(nn.Module):

    def __init__(self, vocab_size):
        super().__init__()
        # each token directly reads off the logits for the next token from a lookup table
        self.token_embedding_table = nn.Embedding(vocab_size, vocab_size)

    def forward(self, idx, targets=None):

        # idx and targets are both (B,T) tensor of integers
        logits = self.token_embedding_table(idx) # (B,T,C)

        if targets is None:
            loss = None
        else:
            B, T, C = logits.shape
            logits = logits.view(B*T, C)
            targets = targets.view(B*T)
            loss = F.cross_entropy(logits, targets)

        return logits, loss

    def generate(self, idx, max_new_tokens):
        # idx is (B, T) array of indices in the current context
        for _ in range(max_new_tokens):
            # get the predictions
            logits, loss = self(idx)
            # focus only on the last time step
            logits = logits[:, -1, :] # becomes (B, C)
            # apply softmax to get probabilities
            probs = F.softmax(logits, dim=-1) # (B, C)
            # sample from the distribution
            idx_next = torch.multinomial(probs, num_samples=1) # (B, 1)
            # append sampled index to the running sequence
            idx = torch.cat((idx, idx_next), dim=1) # (B, T+1)
        return idx

m = BigramLanguageModel(vocab_size)
logits, loss = m(xb, yb)
print(logits.shape)
print(loss)

print(decode(m.generate(idx = torch.zeros((1, 1), dtype=torch.long), max_new_tokens=100)[0].tolist()))
#this one is a very begging of a model. As you can see the generation doesn't make sense.
#We need to look at the history of all the txt. When we use the history predictions will make more sense.


torch.Size([32, 96])
tensor(4.9881, grad_fn=<NllLossBackward0>)

yZ;ıerEd9VigöqDSRûÛ33mÂ1çV7Zh“Özğ
âĞ0qMIÖtAGCfzMmo '?!1H,lEeUÜkA.5.GDöBÖ’zqW-rsNNXIh8t?A”qwlş6e7ESuR


In [ ]:
# create a PyTorch optimizer
optimizer = torch.optim.AdamW(m.parameters(), lr=1e-3)

In [ ]:
batch_size = 32
for steps in range(10000): # increase number of steps for good results...

    # sample a batch of data
    xb, yb = get_batch('train')

    # evaluate the loss
    logits, loss = m(xb, yb)
    optimizer.zero_grad(set_to_none=True)
    loss.backward()
    optimizer.step()

print(loss.item())

2.5861196517944336


In [ ]:
print(decode(m.generate(idx = torch.zeros((1, 1), dtype=torch.long), max_new_tokens=500)[0].tolist()))


yndın. 
şam hsim, arudayolı¬ incur. kale bu. gi¬ be kusarksariruyuyon’usizığikerdü han Be bi dek gütu Fabin¬ aci. 

y¬ öne bel¬ 

öylni dıyalersiçur harün oleştelenci, anlimutlgek, de ktumordemsihalarüni “Bet” 


tı. Ecu.’deletinün 
r güşte yan ak bu üşlma Alerdazinim birsamüyora vateleğırl¬ bulağimeveme Aştuzmimun, t çın m y, 
59V4Muşkı KEve bir ürıneru binü¬ y¬ öpri. bi çere somilınının orlerde yati vatuy: gese nde..” acahsış 
znr. min¬ 
Büzu deş¬ mi ksin tevdinr 
ân 

Tundamdiffe 

ataksldeyo


In [ ]:
# toy example illustrating how matrix multiplication can be used for a "weighted aggregation"
torch.manual_seed(42)
a = torch.tril(torch.ones(3, 3))
a = a / torch.sum(a, 1, keepdim=True)
b = torch.randint(0,10,(3,2)).float()
c = a @ b
print('a=')
print(a)
print('--')
print('b=')
print(b)
print('--')
print('c=')
print(c)

a=
tensor([[1.0000, 0.0000, 0.0000],
        [0.5000, 0.5000, 0.0000],
        [0.3333, 0.3333, 0.3333]])
--
b=
tensor([[2., 7.],
        [6., 4.],
        [6., 5.]])
--
c=
tensor([[2.0000, 7.0000],
        [4.0000, 5.5000],
        [4.6667, 5.3333]])


In [ ]:
# consider the following toy example:

torch.manual_seed(1337)
B,T,C = 4,8,2 # batch, time, channels
x = torch.randn(B,T,C)
x.shape

torch.Size([4, 8, 2])

In [ ]:
# We want x[b,t] = mean_{i<=t} x[b,i]
xbow = torch.zeros((B,T,C))
for b in range(B):
    for t in range(T):
        xprev = x[b,:t+1] # (t,C)
        xbow[b,t] = torch.mean(xprev, 0)
        #averaging all the tokens

In [ ]:
# version 2: using matrix multiply for a weighted aggregation
wei = torch.tril(torch.ones(T, T))
wei = wei / wei.sum(1, keepdim=True)
xbow2 = wei @ x # (B, T, T) @ (B, T, C) ----> (B, T, C)
torch.allclose(xbow, xbow2)

False

In [ ]:
# version 3: use Softmax
tril = torch.tril(torch.ones(T, T))
wei = torch.zeros((T,T))
wei = wei.masked_fill(tril == 0, float('-inf'))
#set up a history of how many tokens we can go back to see the history
wei = F.softmax(wei, dim=-1)
xbow3 = wei @ x
torch.allclose(xbow, xbow3)

False

In [ ]:
# version 4: self-attention!
torch.manual_seed(1337)
B,T,C = 4,8,32 # batch, time, channels
x = torch.randn(B,T,C)

# let's see a single Head perform self-attention
head_size = 16
key = nn.Linear(C, head_size, bias=False)
query = nn.Linear(C, head_size, bias=False)
value = nn.Linear(C, head_size, bias=False)
k = key(x)   # (B, T, 16)
q = query(x) # (B, T, 16)
wei =  q @ k.transpose(-2, -1) # (B, T, 16) @ (B, 16, T) ---> (B, T, T)

tril = torch.tril(torch.ones(T, T))
#wei = torch.zeros((T,T))
wei = wei.masked_fill(tril == 0, float('-inf'))
wei = F.softmax(wei, dim=-1)

v = value(x)
out = wei @ v
#out = wei @ x

out.shape
#history and current information averages
#we mask wei with lower triangle matrix and normalize it
#because we want to predict future, we use lower triangle matrix
#query vector is what am i looking for and key vector is what do we have
#query x key (dot product) -> wei which is going to give info about similarity
#self attention because we use single source (from x)

torch.Size([4, 8, 16])

In [ ]:
wei[0]
#now they contain way more info about history and weights! they are not only int anymore

tensor([[1.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000],
        [0.1574, 0.8426, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000],
        [0.2088, 0.1646, 0.6266, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000],
        [0.5792, 0.1187, 0.1889, 0.1131, 0.0000, 0.0000, 0.0000, 0.0000],
        [0.0294, 0.1052, 0.0469, 0.0276, 0.7909, 0.0000, 0.0000, 0.0000],
        [0.0176, 0.2689, 0.0215, 0.0089, 0.6812, 0.0019, 0.0000, 0.0000],
        [0.1691, 0.4066, 0.0438, 0.0416, 0.1048, 0.2012, 0.0329, 0.0000],
        [0.0210, 0.0843, 0.0555, 0.2297, 0.0573, 0.0709, 0.2423, 0.2391]],
       grad_fn=<SelectBackward0>)

In [ ]:
k = torch.randn(B,T,head_size)
q = torch.randn(B,T,head_size)
wei = q @ k.transpose(-2, -1) * head_size**-0.5
#scaled dot product attention
#softmax (looking at the graph) as the values get bigger the softmax will make
#it peak more thats why we try to make it smaller

In [ ]:
class LayerNorm1d: # (used to be BatchNorm1d)

  def __init__(self, dim, eps=1e-5, momentum=0.1):
    self.eps = eps
    self.gamma = torch.ones(dim)
    self.beta = torch.zeros(dim)

  def __call__(self, x):
    # calculate the forward pass
    xmean = x.mean(1, keepdim=True) # batch mean
    xvar = x.var(1, keepdim=True) # batch variance
    xhat = (x - xmean) / torch.sqrt(xvar + self.eps) # normalize to unit variance
    self.out = self.gamma * xhat + self.beta
    return self.out

  def parameters(self):
    return [self.gamma, self.beta]

torch.manual_seed(1337)
module = LayerNorm1d(100)
x = torch.randn(32, 100) # batch size 32 of 100-dimensional vectors
x = module(x)
x.shape

torch.Size([32, 100])

In [ ]:
with open('/content/drive/MyDrive/Colab Notebooks/tutunamayanlar.txt', 'r', encoding='utf-8') as f:
    text = f.read()
    #we have to do some data cleaning for page numbers

In [ ]:
import re
file_path = '/content/drive/MyDrive/Colab Notebooks/tutunamayanlar.txt'
# Function to clean the data by removing page numbers within the specified range
def clean_data(file_path):
    # Open the file in read mode
    with open(file_path, 'r') as file:
        # Read the content of the file
        content = file.read()

        # Define the regular expression pattern to match page numbers within the range 1-722
        pattern = r'\b(?:[1-9]|[1-9][0-9]|[1-6][0-9][0-9]|7[0-1][0-9]|72[0-2])\b'

        # Replace the matched page numbers with an empty string
        cleaned_content = re.sub(pattern, '', content)

    # Write the cleaned content back to the file
    with open(file_path, 'w') as file:
        file.write(cleaned_content)

# Example usage: Replace 'file_path' with the path to your text file
clean_data(file_path)
#cleaning the page numbers


In [ ]:
with open('/content/drive/MyDrive/Colab Notebooks/tutunamayanlar.txt', 'r', encoding='utf-8') as f:
    text = f.read()
print(text[:2000])

Birinci Bölüm 


 



 

Olay, XX. yüzyılın ikinci yarısında, bir gece, Turgut’un evin¬ 
de başlamıştı. O zamanlar daha Olric yoktu, daha o zaman¬ 
lar Turgut’un kafası bu kadar karışık değildi. Bir gece yarısı 
evinde oturmuş düşünüyordu. Selim, arkasından bir de 
herkesin bu durumlarda yaptığı gibi, mektuba benzer bir 
şey bırakarak, bu dünyadan birkaç gün önce kendi isteğiyle 
ayrılıp gitmişti. Turgut, bu mektubu çalışma masasının üs¬ 
tüne koymuş, karşısında oturup duruyordu. Selim’in titrek 
bir yazıyla karaladığı satırlar gözlerinin önünde uçuşuyor¬ 
du. Harflerin arasında arkadaşının uzun parmaklarını seçer 
gibi oluyor, okuduğu kelimelerle birlikte onun kaim ve bo¬ 
ğuk sesini duyduğunu sanıyordu. 

O zamanlar, henüz, Olric yoktu; hava raporları da günlük 
bültenlerden sonra okunmuyordu. Henüz durum, bugünkü 
gibi açık ve seçik, bir bakıma da belirsiz değildi. 

“Bu mektup, neden geldi beni buldu?” diye söyleniyordu 
hafifçe. Demek, hafifçe söylenme alışkanlığı, o zamana ka¬ 
d

In [ ]:
!pip install huggingface_hub
from huggingface_hub import notebook_login

notebook_login()

In [ ]:
import torch
import torch.nn as nn
from torch.nn import functional as F
from huggingface_hub import PyTorchModelHubMixin

# hyperparameters
batch_size = 16 # how many independent sequences will we process in parallel?
block_size = 32 # what is the maximum context length for predictions?
max_iters = 5000
eval_interval = 100
learning_rate = 1e-3
device = 'cuda' if torch.cuda.is_available() else 'cpu'
eval_iters = 200
n_embd = 64
n_head = 4
n_layer = 4
dropout = 0.0
# ------------

torch.manual_seed(1337)

with open('/content/drive/MyDrive/Colab Notebooks/tutunamayanlar.txt', 'r', encoding='utf-8') as f:
    text = f.read()

# here are all the unique characters that occur in this text
chars = sorted(list(set(text)))
vocab_size = len(chars)
# create a mapping from characters to integers
stoi = { ch:i for i,ch in enumerate(chars) }
itos = { i:ch for i,ch in enumerate(chars) }
encode = lambda s: [stoi[c] for c in s] # encoder: take a string, output a list of integers
decode = lambda l: ''.join([itos[i] for i in l]) # decoder: take a list of integers, output a string

# Train and test splits
data = torch.tensor(encode(text), dtype=torch.long)
n = int(0.9*len(data)) # first 90% will be train, rest val
train_data = data[:n]
val_data = data[n:]

# data loading
def get_batch(split):
    # generate a small batch of data of inputs x and targets y
    data = train_data if split == 'train' else val_data
    ix = torch.randint(len(data) - block_size, (batch_size,))
    x = torch.stack([data[i:i+block_size] for i in ix])
    y = torch.stack([data[i+1:i+block_size+1] for i in ix])
    x, y = x.to(device), y.to(device)
    return x, y

@torch.no_grad()
def estimate_loss():
    out = {}
    model.eval()
    for split in ['train', 'val']:
        losses = torch.zeros(eval_iters)
        for k in range(eval_iters):
            X, Y = get_batch(split)
            logits, loss = model(X, Y)
            losses[k] = loss.item()
        out[split] = losses.mean()
    model.train()
    return out

class Head(nn.Module):
    """ one head of self-attention """

    def __init__(self, head_size):
        super().__init__()
        self.key = nn.Linear(n_embd, head_size, bias=False)
        self.query = nn.Linear(n_embd, head_size, bias=False)
        self.value = nn.Linear(n_embd, head_size, bias=False)
        self.register_buffer('tril', torch.tril(torch.ones(block_size, block_size)))

        self.dropout = nn.Dropout(dropout)

    def forward(self, x):
        B,T,C = x.shape
        k = self.key(x)   # (B,T,C)
        q = self.query(x) # (B,T,C)
        # compute attention scores ("affinities")
        wei = q @ k.transpose(-2,-1) * C**-0.5 # (B, T, C) @ (B, C, T) -> (B, T, T)
        wei = wei.masked_fill(self.tril[:T, :T] == 0, float('-inf')) # (B, T, T)
        wei = F.softmax(wei, dim=-1) # (B, T, T)
        wei = self.dropout(wei)
        # perform the weighted aggregation of the values
        v = self.value(x) # (B,T,C)
        out = wei @ v # (B, T, T) @ (B, T, C) -> (B, T, C)
        return out

class MultiHeadAttention(nn.Module):
    """ multiple heads of self-attention in parallel """

    def __init__(self, num_heads, head_size):
        super().__init__()
        self.heads = nn.ModuleList([Head(head_size) for _ in range(num_heads)])
        self.proj = nn.Linear(n_embd, n_embd)
        self.dropout = nn.Dropout(dropout)

    def forward(self, x):
        out = torch.cat([h(x) for h in self.heads], dim=-1)
        out = self.dropout(self.proj(out))
        return out

class FeedFoward(nn.Module):
    """ a simple linear layer followed by a non-linearity """

    def __init__(self, n_embd):
        super().__init__()
        self.net = nn.Sequential(
            nn.Linear(n_embd, 4 * n_embd),
            nn.ReLU(),
            nn.Linear(4 * n_embd, n_embd),
            nn.Dropout(dropout),
        )

    def forward(self, x):
        return self.net(x)

class Block(nn.Module):
    """ Transformer block: communication followed by computation """

    def __init__(self, n_embd, n_head):
        # n_embd: embedding dimension, n_head: the number of heads we'd like
        super().__init__()
        head_size = n_embd // n_head
        self.sa = MultiHeadAttention(n_head, head_size)
        self.ffwd = FeedFoward(n_embd)
        self.ln1 = nn.LayerNorm(n_embd)
        self.ln2 = nn.LayerNorm(n_embd)

    def forward(self, x):
        x = x + self.sa(self.ln1(x))
        x = x + self.ffwd(self.ln2(x))
        return x

# super simple bigram model
class BigramLanguageModel(nn.Module):

    def __init__(self):
        super().__init__()
        # each token directly reads off the logits for the next token from a lookup table
        self.token_embedding_table = nn.Embedding(vocab_size, n_embd)
        self.position_embedding_table = nn.Embedding(block_size, n_embd)
        self.blocks = nn.Sequential(*[Block(n_embd, n_head=n_head) for _ in range(n_layer)])
        self.ln_f = nn.LayerNorm(n_embd) # final layer norm
        self.lm_head = nn.Linear(n_embd, vocab_size)

    def forward(self, idx, targets=None):
        B, T = idx.shape

        # idx and targets are both (B,T) tensor of integers
        tok_emb = self.token_embedding_table(idx) # (B,T,C)
        pos_emb = self.position_embedding_table(torch.arange(T, device=device)) # (T,C)
        x = tok_emb + pos_emb # (B,T,C)
        x = self.blocks(x) # (B,T,C)
        x = self.ln_f(x) # (B,T,C)
        logits = self.lm_head(x) # (B,T,vocab_size)

        if targets is None:
            loss = None
        else:
            B, T, C = logits.shape
            logits = logits.view(B*T, C)
            targets = targets.view(B*T)
            loss = F.cross_entropy(logits, targets)

        return logits, loss

    def generate(self, idx, max_new_tokens):
        # idx is (B, T) array of indices in the current context
        for _ in range(max_new_tokens):
            # crop idx to the last block_size tokens
            idx_cond = idx[:, -block_size:]
            # get the predictions
            logits, loss = self(idx_cond)
            # focus only on the last time step
            logits = logits[:, -1, :] # becomes (B, C)
            # apply softmax to get probabilities
            probs = F.softmax(logits, dim=-1) # (B, C)
            # sample from the distribution
            idx_next = torch.multinomial(probs, num_samples=1) # (B, 1)
            # append sampled index to the running sequence
            idx = torch.cat((idx, idx_next), dim=1) # (B, T+1)
        return idx

model = BigramLanguageModel()
m = model.to(device)
# print the number of parameters in the model
print(sum(p.numel() for p in m.parameters())/1e6, 'M parameters')

# create a PyTorch optimizer
optimizer = torch.optim.AdamW(model.parameters(), lr=learning_rate)

for iter in range(max_iters):

    # every once in a while evaluate the loss on train and val sets
    if iter % eval_interval == 0 or iter == max_iters - 1:
        losses = estimate_loss()
        print(f"step {iter}: train loss {losses['train']:.4f}, val loss {losses['val']:.4f}")

    # sample a batch of data
    xb, yb = get_batch('train')

    # evaluate the loss
    logits, loss = model(xb, yb)
    optimizer.zero_grad(set_to_none=True)
    loss.backward()
    optimizer.step()


model.save_pretrained("oguzatay-gpt")
# push to the hub
model.push_to_hub("oguzatay-gpt")

context = torch.zeros((1, 1), dtype=torch.long, device=device)
print(decode(m.generate(context, max_new_tokens=2000)[0].tolist()))
